acts = {
    "Select an Act": None,
    "THE BHARATIYA NYAYA SANHITA, 2023": "BNS",
    "THE BHARATIYA NAGARIK SURAKSHA SANHITA, 2023":"BNSS",
    "THE CODE OF CRIMINAL PROCEDURE, 1973":"CrPC",
    "THE PROTECTION OF WOMEN FROM DOMESTIC VIOLENCE ACT, 2005":"DVA",
    "THE INDIAN PENAL CODE":"IPC",
    "THE INDECENT REPRESENTATION OF WOMEN (PROHIBITION) ACT, 1986":"IRWA",
    "THE IMMORAL TRAFFIC (PREVENTION) ACT, 1956":"ITA",
    "THE INFORMATION TECHNOLOGY ACT, 2000":"ITAct",
    "THE JUVENILE JUSTICE (CARE AND PROTECTION OF CHILDREN) ACT, 2015":"JJA",
    "THE NATIONAL INVESTIGATION AGENCY ACT, 2008":"NIA",
    "THE NATIONAL SECURITY ACT, 1980":"NSA",
    "THE PREVENTION OF CORRUPTION ACT, 1988":"PCA",
    "THE PREVENTION OF MONEY-LAUNDERING ACT, 2002":"PMLA",
    "THE PROTECTION OF CHILDREN FROM SEXUAL OFFENCES ACT, 2012":"POSCO",
    "THE SCHEDULED CASTES AND THE SCHEDULED TRIBES (PREVENTION OF ATROCITIES) ACT, 1989":"SCSTAct",
    "THE UNLAWFUL ACTIVITIES (PREVENTION) ACT, 1967":"UAPA"
}

print(list(acts.keys()))
print(type(acts.keys))
